[book]
title = "Örneklerle Rust"
description = "Örneklerle Rust (RBE), çeşitli Rust kavramlarını ve standart kitaplıkları gösteren çalıştırılabilir örneklerden oluşan bir koleksiyondur."
author = "Rust Topluluğu"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/rust-lang-tr/rust-by-example-tr"

[rust]
edition = "2022"
