name: CI
on: [push, pull_request]

jobs:
  test:
    name: Testleri çalıştırın
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Rustup'ı güncelleyin
      run: rustup self update

    - name: Rust'ı Yükleyin
      run: |
        rustup set profile minimal
        rustup toolchain install nightly -c rust-docs
        rustup default nightly

    - name: mdbook'u indirin
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> ${GITHUB_PATH}

    - name: Sürümü bildirin
      run: |
        rustup --version
        rustc -Vv
        mdbook --version

    - name: Testleri çalıştırın
      run: mdbook test

    - name: HTML Oluştur
      run: mdbook build

    - name: Kırık linkleri kontrol edin
      run: |
        curl -sSLo linkcheck.sh \
          https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
        sh linkcheck.sh --all rust-by-example

    - name: Eser Yükle
      uses: actions/upload-artifact@v1
      with:
        name: rust-by-example
        path: book
